---
- hosts: all
  gather_facts: yes
  connection: local
  vars_files:
     - group_vars/all
  tasks:
  - name: Set the test provider
    set_fact:
     provider:
      host: "{{ inventory_hostname}}"
      username: "{{ username }}"
      password: "{{ password }}"
      authorize: yes
      auth_pass: "{{ auth_pass }}"
      timeout: 30

  - name: Get the running-config
    ios_interface:
       provider: "{{ provider }}"
       name: Ethernet0/2
       description: "Configured by ansible playbook"
       enabled: True


