language: python
python:
  - "2.6"
  - "2.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python2.7-dev
#notifications:
#  email:
#    - someone@somewhere.org
install:
  - pip install paramiko
  - pip install jinja2
  - pip install PyYAML
# command to run tests
script: make tests
