sudo: required
services:
  - docker
language: python
env:
  global:
    - DOCKER_ROOT=test/integration/docker/
  matrix:
    - DOCKER_FILE=Dockerfile.ubuntu-12.04 DOCKER_NAME=test_ubuntu_12.04
    #- TOKENV=py24
    #- TOXENV=py26
    #- TOXENV=py27
    #- TOXENV=py34
#addons:
#  apt:
#    sources:
#      - deadsnakes
#    packages:
#      - python2.4
before_install:
  - docker pull ubuntu:12.04
install:
  - pip install tox PyYAML Jinja2 sphinx
script:
#- if test x"$TOKENV" != x'py24' ; then  tox ; fi
#- if test x"$TOKENV" = x'py24' ; then python2.4 -V && python2.4 -m compileall -fq -x 'module_utils/(a10|rax|openstack|ec2|gce).py' lib/ansible/module_utils ; fi
  #- make -C docsite all
- cd $DOCKER_ROOT && cp $DOCKER_FILE Dockerfile && docker build -t ansible/$DOCKER_NAME .
- |
  if [ -n $DOCKER_FILE ]; then 
      cd $TRAVIS_BUILD_DIR
      docker run --privileged=true --name ansible_test -i -t -v $PWD:/ansible ansible/$DOCKER_NAME:latest & 
      docker exec -i -t $DOCKER_NAME:latest /ansible/test/integration/docker/init.sh
      docker stop $DOCKER_NAME
  fi
after_success:
  - coveralls
