---
- name: test my new module
  hosts: localhost
  tasks:
  - name: Create a VM on TACP
    tacp_instance:
      api_key: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJYYW5kZXIgTWFkc2VuIFR1ZSBBcHIgMjEgMTg6Mjg6MzAgVVRDIDIwMjAifQ.lMQzOVVozwPq38C43zJ83B8hDQKHeW9DESkmQx_cc3t22vBLRVVC2CAQIxIkVmKAYprrgkBWtXUJG8wz33q_cg
      name: Test_VM
      state: present
      datacenter: OTA_TEST
      mz: MZ 1
      template: CentOS 7 - Jenkins - Lenovo Template
      storage_pool: Pool 1
      vcpu_cores: 1
      memory: 2g
      disks:
        - size_gb: 20
      nics:
        - name: vNIC 0
          type: VNET
          network: OTA_VNET
    register: testout

  - name: Output
    debug:
      msg: '{{ testout }}'