
---
- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: zimsacr
    location: eastus
    acr_name: zimsacrxisiidid
  #roles:
  #  - modules
  tasks:

    - name: Make sure Deep Learning VM Resource Group Exists
      azure_rm_xxvirtualmachineextension:
        resource_group: "{{ resource_group }}"
        name: "{{ location }}"

