---
# File:

- hosts: 127.0.0.1
  connection: local
  tasks:
  - cloudfront_distribution:
      state: present
      distribution_id: E2A8R24XAXMGAG
      comment: test comment
      tags:
        - Name: example distribution
        - Project: example project
        - Priority: 111
