# ansible-pull setup
#
# on remote hosts, set up ansible to run periodically using the latest code
# from a particular git repo, in pull based fashion, inverting Ansible's
# usual push-based operating mode.
#
# This particular pull based mode is ideal for:
#
# (A) massive scale out
# (B) continual system remediation
#
# DO NOT RUN THIS AGAINST YOUR HOSTS WITHOUT CHANGING THE repo_url
# TO SOMETHING YOU HAVE PERSONALLY VERIFIED
#
---

- hosts: pull_mode_hosts
  user: root

  vars:
    # schedule for cronjob; 30m interval is typical of other cm tools
    schedule: '*/30 * * * *'

    # user that runs ansible-pull from cron job
    cron_user: root

    # directory where ansible is installed, best used with git clone installs of ansible
    installdir: /usr/local/ansible

    # directory where playbook git repo will be cloned and where playbook runs will be started
    workdir: /var/lib/ansible

    # directory where the cronjob log file will be written
    logdir: /var/log/ansible

    # crobjob log file
    logfile: ${logdir}/ansible-pull.log

    # playbook git repo URL -- REQUIRED: YOU MUST CHANGE THIS
    # Example 1: repo_url: git://github.com/<username>/<repo_name>.git
    # Example 2: repo_url: https://github.com/<username>/<repo_name>.git
    # Example 3: repo_url: https://<username>:<password>@github.com/<username>/<repo_name>.git
    repo_url: SUPPLY_YOUR_OWN_GIT_URL_HERE

  tasks:
  - name: install ansible from git repo
    action: git repo=https://github.com/ansible/ansible.git dest=$installdir

  # written with ubuntu 12.04 in mind
  - name: install ansible dependencies
    action: apt pkg=$item
    with_items:
    - python-jinja2
    - python-yaml
    - python-paramiko

  - name: symlink ansible
    action: file src=$installdir/bin/ansible dest=/usr/local/bin/ansible owner=root group=root state=link

  - name: symlink ansible-playbook
    action: file src=$installdir/bin/ansible-playbook dest=/usr/local/bin/ansible-playbook owner=root group=root state=link

  - name: symlink ansible-pull
    action: file src=$installdir/bin/ansible-pull dest=/usr/local/bin/ansible-pull owner=root group=root state=link

  - name: create /etc/ansible directory
    action: file path=/etc/ansible owner=root group=root state=directory

  - name: create $logdir directory
    action: file path=$logdir owner=root group=root state=directory

  - name: create $workdir directory
    action: file path=$workdir state=directory owner=root group=root mode=0751

  - name: create ansible hosts file
    action: copy src=templates/etc_ansible_hosts.ansible-pull dest=/etc/ansible/hosts owner=root group=root mode=0644

  - name: configure logrotate
    action: template src=templates/etc_logrotate.d_ansible-pull.j2 dest=/etc/logrotate.d/ansible-pull owner=root group=root mode=0644
    tags:
    - logrotate

  - name: configure cronjob
    action: template src=templates/etc_cron.d_ansible-pull.j2 dest=/etc/cron.d/ansible-pull owner=root group=root mode=0644
    tags:
    - cronjob
