
# This task for running configuration on a switch

#- name: enter `enable` configuration mode
#  command: enable
- name: run some configuration command - enabling telnet-server
  mlnxos_config:
    lines: 
      - telnet-server enable
    provider:
      host: "{{ inventory_hostname }}"
      username: admin
      password: admin
      port: 22
      timeout: 10
      authorize: yes
    username: admin
    password: admin

