
# This task for configuring lossless RoCE on switch

- name: run some lossy roce configuration commands
  mlnxos_config:
    lines:
      # Set roce lossy pool 50%:
      - traffic pool roce_lossy type lossy
      - traffic pool roce_lossy memory percent 50.00
      - traffic pool roce_lossy map switch-priority 3
      # Set qos trust L3 in all ports
      - interface ethernet 1/1-1/4 qos trust L3
      # Set ECN in all ports both in traffic Class 0 & 3
      - interface ethernet 1/1-1/32 traffic-class 0 congestion-control ecn minimum-absolute 150 maximum-absolute 1500
      - interface ethernet 1/1-1/32 traffic-class 3 congestion-control ecn minimum-absolute 150 maximum-absolute 1500
      # Set CNPs traffic class 6 to strict priority!
      - interface ethernet 1/1-1/32 traffic-class 6 dcb ets strict
      # exit configuration mode
      - exit
    provider:
      host: "{{ inventory_hostname }}"
      username: admin
      password: admin
      port: 22
      timeout: 10
      authorize: yes
    username: admin
    password: admin

