# This task for running configuration on a switch
- name: run add vlan
  mlnxos_vlan:
    vlan_id: 6
    state: present
    authorize: yes
    provider:
      host: "{{ inventory_hostname }}"
      username: admin
      password: admin
      port: 22
      timeout: 10

- name: run remove vlan
  mlnxos_vlan:
    vlan_id: 6
    state: absent
    authorize: yes
    provider:
      host: "{{ inventory_hostname }}"
      username: admin
      password: admin
      port: 22
      timeout: 10

- name: run add interfaces to vlan 
  mlnxos_vlan:
    vlan_id: 6 
    state: present 
    interfaces:
      - Eth1/6
      - Eth1/7
    mode: hybrid 
    authorize: yes
    provider:
      host: "{{ inventory_hostname }}"
      username: admin
      password: admin
      port: 22
      timeout: 10
