
# This task for running configuration on a switch

#- name: enter `enable` configuration mode
#  command: enable

- name: run add switchports to vlan 
  mlnxos_vlan:
    vlan_id: 6 
    state: present 
    switchport: Eth1/6,Eth1/7
    mode: hybrid 
    authorize: yes
    provider:
      host: "{{ inventory_hostname }}"
      username: admin
      password: admin
      port: 22
      timeout: 10

- name: run add switchport to vlan
  mlnxos_vlan:
    vlan_id: 5
    state: present
    switchport: Eth1/5
    mode: hybrid
    authorize: yes
    provider:
      host: "{{ inventory_hostname }}"
      username: admin
      password: admin
      port: 22
      timeout: 10

- name: run remove switchports from vlan
  mlnxos_vlan:
    vlan_id: 6
    state: absent
    switchport: Eth1/6,Eth1/7
    mode: hybrid
    authorize: yes
    provider:
      host: "{{ inventory_hostname }}"
      username: admin
      password: admin
      port: 22
      timeout: 10

- name: run remove switchport from vlan
  mlnxos_vlan:
    vlan_id: 5
    state: absent
    switchport: Eth1/5
    mode: hybrid
    authorize: yes
    provider:
      host: "{{ inventory_hostname }}"
      username: admin
      password: admin
      port: 22
      timeout: 10

