trigger:
  batch: true
  branches:
    include:
      - devel
      - stable-*

pr:
  autoCancel: true
  branches:
    include:
      - devel
      - stable-*

schedules:
  - cron: 0 7 * * *
    displayName: Nightly
    always: true
    branches:
      include:
        - devel
        - stable-*

variables:
  - name: checkoutPath
    value: ansible
  - name: coverageBranches
    value: devel
  - name: entryPoint
    value: test/utils/shippable/shippable.sh
  - name: fetchDepth
    value: 500

resources:
  containers:
    - container: default
      image: quay.io/ansible/azure-pipelines-test-container:3.0.0

pool: Standard

stages:
  - stage: Remote
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          targets:
            - name: macOS 12.0
              test: macos/12.0
            - name: RHEL 7.9
              test: rhel/7.9
            - name: RHEL 8.6 py36
              test: rhel/8.6@3.6
            - name: RHEL 8.6 py38
              test: rhel/8.6@3.8
            - name: RHEL 9.0
              test: rhel/9.0
            - name: FreeBSD 12.3
              test: freebsd/12.3
            - name: FreeBSD 13.1
              test: freebsd/13.1
          groups:
            - 1
            - 2
            - 3
            - 4
            - 5
  - stage: Docker
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          testFormat: linux/{0}
          targets:
            - name: Alpine 3
              test: alpine3
            - name: CentOS 7
              test: centos7
            - name: Fedora 35
              test: fedora35
            - name: Fedora 36
              test: fedora36
            - name: openSUSE 15
              test: opensuse15
            - name: Ubuntu 20.04
              test: ubuntu2004
            - name: Ubuntu 22.04
              test: ubuntu2204
          groups:
            - 1
            - 2
            - 3
            - 4
            - 5
  - stage: Galaxy
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: Python {0}
          testFormat: galaxy/{0}/1
          targets:
            - test: 3.8
            - test: 3.9
            - test: '3.10'
            - test: 3.11
  - stage: Generic
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: Python {0}
          testFormat: generic/{0}/1
          targets:
            - test: 3.8
            - test: 3.9
            - test: '3.10'
            - test: 3.11
  - stage: Summary
    condition: succeededOrFailed()
    dependsOn:
      - Remote
      - Docker
      - Galaxy
      - Generic
    jobs:
      - template: templates/coverage.yml
