trigger:
  batch: true
  branches:
    include:
      - devel
      - stable-*

pr:
  autoCancel: true
  branches:
    include:
      - devel
      - stable-*

schedules:
  - cron: 0 7 * * *
    displayName: Nightly
    always: true
    branches:
      include:
        - devel
        - stable-*

variables:
  - name: checkoutPath
    value: ansible
  - name: coverageBranches
    value: devel
  - name: pipelinesCoverage
    value: coverage
  - name: entryPoint
    value: test/utils/shippable/shippable.sh
  - name: fetchDepth
    value: 500

resources:
  containers:
    - container: default
      image: quay.io/ansible/azure-pipelines-test-container:1.9.0

pool: Standard

stages:
  - stage: Docker
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          testFormat: linux/{0}
          targets:
            - name: Ubuntu 20.04
              test: ubuntu2004
          groups:
            - 1
  - stage: Summary
    condition: succeededOrFailed()
    dependsOn:
      - Docker
    jobs:
      - template: templates/coverage.yml
