trigger:
  batch: true
  branches:
    include:
      - devel
      - stable-*

pr:
  autoCancel: true
  branches:
    include:
      - devel
      - stable-*

schedules:
  - cron: 0 7 * * *
    displayName: Nightly
    always: true
    branches:
      include:
        - devel
        - stable-*

variables:
  - name: checkoutPath
    value: ansible
  - name: coverageBranches
    value: devel
  - name: entryPoint
    value: .azure-pipelines/commands/entry-point.sh
  - name: fetchDepth
    value: 500
  - name: defaultContainer
    value: quay.io/ansible/azure-pipelines-test-container:4.0.1

pool: Flexible

stages:
  - stage: Test
    dependsOn: []
    jobs:
      - job: Test1
        steps:
          - script: ip addr show
          - script: curl -s        'https://api64.ipify.org'; echo
          - script: curl -s --ipv4 'https://api64.ipify.org'; echo
          - script: curl -s --ipv6 'https://api64.ipify.org'; echo
      - job: Test2
        steps:
          - script: ip addr show
          - script: curl -s        'https://api64.ipify.org'; echo
          - script: curl -s --ipv4 'https://api64.ipify.org'; echo
          - script: curl -s --ipv6 'https://api64.ipify.org'; echo
