package:
  name: ansible
  version: "1.9.4.1"

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', '0') }}

source:
  path: ../
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - ansible = ansible:main
    #
    # Would create an entry point called ansible that calls ansible.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - paramiko
    - jinja2
    - pyyaml
    - setuptools
    - pycrypto >=2.6

  run:
    - python
    - paramiko
    - jinja2
    - pyyaml
    - setuptools
    - pycrypto >=2.6

test:
  # Python imports
  imports:
    - ansible

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://ansible.com/
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'Radically simple IT automation'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
